name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup V
        uses: nocturlab/setup-vlang-action@v1.2.0
        #with:
        #  # The V version to download and use.
        #  v-version: # optional, default is lates

      - name: Build
        run: v . -shared
